### ISSUE TITLE
Top navigation requires 2-click

### ISSUE THREAD

**Issue by ptager** [AdobeDocs/experience-manager-cloud-service.en#6] opened 2020-01-23 19:06 UTC
Issue in help/overview/home.md

Need to click twice on the top navigation option 'Adobe Experience Manager as a Cloud Service' to go back to the top level topics outline.

**Comment by bohnertchris** [comment] 2020-01-24 07:24
Thank you for the issue, @ptager . However I need a bit more information. From what I understand you are on 

https://docs.adobe.com/content/help/en/experience-manager-cloud-service/overview/home.html

And you click on the link 'Adobe Experience Manager as a Cloud Service' at the top of the page (see illustration). Is this correct?

<img width="1552" alt="screen-shot 2020-01-24 at 08 18 44" src="https://user-images.githubusercontent.com/38424477/73051357-dc3edf80-3e82-11ea-9c09-0fc0bfe3e717.png">

Where does this take you after one click? I.e. are you on the same page when you have to click the second time? I ask because when on that page and clicking the link marked in the illustration, I am taken back to the main page as expected with a single click:

https://docs.adobe.com/content/help/en/experience-manager-cloud-service/landing/home.html

Thanks for further information.

**Comment by ptager** [comment] 2020-01-24 22:54
Hi Chris,

On the first click, nothing happens. I’m using Chrome on Windows.

Thanks,
Pierre

**Comment by bohnertchris** [comment] 2020-01-27 09:01
Hello @ptager . Unfortunately, based on the steps you confirmed to me above, I was not able to reproduce this behavior. It works for me as expected in Safari, Vivaldi, Opera, and Firefox on Mac as well as Chrome and Edge on Windows.

This is likely a caching issue in your browser. I am closing this ticket for now. Thank you for reporting it.

**Closed by bohnertchris** 2020-01-27 09:01 UTC
Labels: question
