### ISSUE TITLE
Tools > Operations is not available in the cloud

### ISSUE THREAD

**Issue by swaroop61** [AdobeDocs/experience-manager-cloud-service.en#69] opened 2023-03-20 02:45 UTC
Issue in ./en/help/operations/asynchronous-jobs.md

Issue Description:
For Aem in cloud, the Operations option is not visible

example: these instructions on this page do not work in cloud.

Global Navigation -> Tools -> Operations -> Jobs
Tools > Operations > Web Console

Label: DocBugBlitz2023

**Comment by bohnertchris** [comment] 2023-03-21 13:13
This is a duplicate of #71

**Closed as completed by bohnertchris** 2023-03-21 13:13 UTC
Labels: Customer Care, Duplicate
