### ISSUE TITLE
ReferrerFilter must not be edited directly

### ISSUE THREAD

**Issue by ackoch** [AdobeDocs/experience-manager-cloud-service.en#198] opened 2024-07-26 11:49 UTC
Issue in ./help/headless/deployment/referrer-filter.md

According to [1] one can add new hostnames to the ReferrerFilter by providing an according OSGi config as:

**org.apache.sling.security.impl.ReferrerFilter.cfg.json**

I don’t think this is 100% correct, though as this could overwrite the configuration provided by engineering as can be seen in the 

Developer console:

```
- pid: "org.apache.sling.security.impl.ReferrerFilter"
  properties:
    allow.hosts.regexp:
    - "https://.*\\.adobe\\.com:443"
    - "https://.*\\.adobe\\.net:443"
    - "https://.*\\.workfront\\.com:443"
    - "https://.*\\.workfront-dev\\.com:443"
    - "https://.*\\.dev\\.workfront\\.tech:443"
- pid: "org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl"
```

So.. something else would probably stop working.

I *believe* the better approach is to provide an amendment config.. In general this seems to always be the better idea. Please x-check with engineering and don't take my word for it. I am following my intuition, only. 

[1] https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/headless/deployment/referrer-filter

**Comment by ackoch** [comment] 2024-07-26 12:11
Please refer to https://adobe-acs.slack.com/archives/C012DL53XPG/p1721994323239509 for details

**Comment by aheim0** [comment] 2024-07-26 13:27
Thanks for raising this - we will review.

**Comment by aheim0** [comment] 2024-07-26 13:27
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment] 2024-08-09 07:45
Thank you for raising this, your suspicions have been confirmed and the issue is now awaiting feedback from another team.

As they operate to a different schedule we are closing this issue now, please follow the CQDOC issue for ongoing progress.

**Closed as completed by aheim0** 2024-08-09 07:45 UTC
Labels: Bug, Tracked

**Comment by aheim0** [comment] 2024-10-10 10:09
@ackoch Thanks for raising this. Some documentation updates have been made (will be published soon), and the development team are making further investigations from their side.
